---
title: "HDI-M and GINI in Brazil \n (1991, 2000, 2010)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F,  message=FALSE)
```

# Load libraries
```{r}
library(tidyverse)
library(janitor)
library(brmap)
```

# Load data
```{r}
idh_gini = tempfile(fileext = ".xlsx")
dataURL <- "https://github.com/ronycoelho/databases/raw/master/idh_census.xlsx"

download.file(dataURL, destfile=idh_gini, mode='wb')

idh_gini <- readxl::read_excel(idh_gini, sheet =2) %>% 
  clean_names() %>% 
  select(ano,	codmun7, gini, idhm)

dt <- brmap_municipio %>% 
  inner_join(idh_gini, by = c("municipio_cod" = "codmun7"))
```

# Theme map
```{r}
theme_map_br <- theme(panel.background = element_rect(fill = "transparent"), 
        panel.grid.major = element_line(color = "transparent"), 
        axis.text.x = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks = element_blank(),
        legend.position = "bottom", 
        #legend.justification = c(1, 1),
        legend.direction = "horizontal",
        legend.margin = margin(5, 50, 5, 50),
        legend.background = element_blank(),
        legend.text = element_text(size = 12),
        legend.title = element_text(size=12),
        plot.title=element_text(hjust=0, vjust=0, face='bold'))
```

# Plot HDI-M (1991, 2000, 2010)
```{r fig.height=10, fig.width=10}
ggplot(dt)+
  geom_sf(aes(fill=idhm), colour = alpha("white", .2), lty=3)+
  scale_fill_viridis_c("HDI-M", option = "inferno")+
  geom_sf(data=brmap::brmap_brasil, fill=NA, color = "black")+
  geom_sf(data=brmap::brmap_estado, fill=NA, color = "black")+
  theme_map_br +
  facet_wrap(~ano)
```

# Plot GINI (1991, 2000, 2010)
```{r fig.height=10, fig.width=10}
X11()
ggplot(dt)+
  geom_sf(aes(fill=gini), colour = alpha("white", .2), lty=3)+
  scale_fill_viridis_c("GINI", option = "inferno", direction = -1)+
  geom_sf(data=brmap::brmap_brasil, fill=NA, color = "black")+
  geom_sf(data=brmap::brmap_estado, fill=NA, color = "black")+
  theme_map_br +
  facet_wrap(~ano)
```




